background {
    monitor =
    path = ~/Pictures/wallpapers/night_gas_station.png
}

input-field {
    monitor =
    size = 15%, 5%
    outline_thickness = 4

    outer_color = rgba(ff4365ee) 
    inner_color = rgba(ff436544) 
    
    check_color= rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(13, 44, 84)
    fade_on_empty = false
    rounding = 15

    position = 0, 0
    halign = center
    valign = center
}
